### PR TITLE
Update code to work with newer LTSs and GHC 8.6

### PR DESCRIPTION
**Pull request by denibertovic**

### CODE REVIEW

**Comment by denibertovic** [comment]
@JustusAdam Let me know if you have any insight here. I'm currently using this patch to get unstuck with my project that's using `marvin` but I'd be happy to help with a proper fix.

**Comment by JustusAdam** [comment]
I don't think there's much we can do here beyond the fix that you applied. A more general fix would be fixing JustusAdam/marvin-interpolate#4, but that seems a lot more complicated. Although that is an important issue to fix, because it makes the interpolation hard to use. 
For the time being my recommendation for a more general fix is this: If you are using infix expressions in an interpolated expression and you get this error, parenthesize. That should take care of it. So in the example you posted that would be `response^.(responseStatus.statusMessage)` instead of `response^.responseStatus.statusMessage`. Its a bit ugly, but probably the best we can do in the short term

**Comment by denibertovic** [comment]
@JustusAdam Do you want me to apply the parenthesis in this PR instead of using `view` ? I mean we still need to apply something here otherwise the package doesn't compile. I assume it would be prudent to add a note to the docs as well. 

I'm not sure what's going on with the CI failures though?

**Comment by JustusAdam** [comment]
I don't really have a preference either way. And yes, a note would probably be a good idea.

I don't know either what the CI failure comes from, but it does not appear to be related to the changes.

**Pull request merged**
